### ISSUE TITLE
About bird-eye-view

### ISSUE THREAD

**Issue by DRosemei** [apple/ml-gsn#8]
Thanks for your great work, and I want to know whether your model could generate bird-eye-view scenes or not. Would it be hard for NeRF to generate it?

**Comment by TDeVries** [comment]
Hello DRosemei,

Yes, you should be able to generate something that looks like a bird-eye-view of the scene. One option is to simply query the network for rays that look straight down on the scene from above, and maybe adjust the starting point of the rays so that they skip the ceiling.

We have implemented a method that does something similar to this called `get_floorplans`: https://github.com/apple/ml-gsn/blob/main/utils/callbacks.py#L107 It works a bit differently than the method I described above in that it first backprojects rendered images into a 3D voxel grid and then takes the first visible pixel when viewed from above (again ignoring the ceiling).

**Comment by DRosemei** [comment]
> Hello DRosemei,
> 
> Yes, you should be able to generate something that looks like a bird-eye-view of the scene. One option is to simply query the network for rays that look straight down on the scene from above, and maybe adjust the starting point of the rays so that they skip the ceiling.
> 
> We have implemented a method that does something similar to this called `get_floorplans`: https://github.com/apple/ml-gsn/blob/main/utils/callbacks.py#L107 It works a bit differently than the method I described above in that it first backprojects rendered images into a 3D voxel grid and then takes the first visible pixel when viewed from above (again ignoring the ceiling).

Thanks for your reply and I will try it :)
